### ISSUE TITLE
Further on LogDensityRejectErrors

### ISSUE THREAD

**Issue by goedman** [chriselrod/ProbabilityModels.jl#3]
Chris,

Finally I'm satisfied with my setup for the performance numbers and I'll send you the results later today.

This new issue is a continuation of the errors I have occasionally seen:
```
> That error is within DynamicHMC, not the logdensity. So I don't imagine such a wrapper will
> help in this case.
> ProbabilityModel's ValueGradient methods check to make sure the logdensity and gradient 
> isfinite, returning -Inf as the density if either aren't. This behaves fairly similarly to 
> LogDensityRejectErrors.
```
In StatisticalModeling there is an R model:
```
## R code 10.14
m10.4 <- ulam(
    alist(
        pulled_left ~ dbinom( 1 , p ) ,
        logit(p) <- a[actor] + (bp + bpC*condition)*prosoc_left ,
        a[actor] ~ dnorm(0,10),
        bp ~ dnorm(0,10),
        bpC ~ dnorm(0,10)
    ) ,
    data=list(pulled_left=d$pulled_left, prosoc_left=d$prosoc_left, condition=d$condition,
      actor=d$actor) ,
    chains=2 , iter=2500 , warmup=500 )
```

It turns out this [model](https://github.com/StatisticalRethinkingJulia/StanModels.jl/blob/master/scripts/10/m10.04s.jl) runs ok in CmdStan but currently shows a bias in [DynamicHMC](https://github.com/StatisticalRethinkingJulia/DynamicHMCModels.jl/blob/master/scripts/10/m10.04d1.jl). The [link](https://github.com/tpapp/DynamicHMC.jl/issues/42#issue-427071164) to the bug report is here (also gives the data file and the DynamicHMC based script).

I wonder if PM/dHMC would handle this case. In the middle of the file is where I encapsulate ADgradient() with LogDensityRejectErrors():

```
do_stresstest = false

#ad = :Flux
ad = :ForwardDiff
#ad = :ReverseDiff

if do_stresstest
  ∇P = ADgradient(:ForwardDiff, P);
  #st = LogDensityProblems.stresstest(p, N=1000, scale=1.0)
  #display(st)
else
  ∇P = LogDensityRejectErrors(ADgradient(ad, P));
end  
```

Would this be a good case and helpful to analyze with PM/dHMC? I would also be very interested how you would model this in PM.

**Comment by chriselrod** [comment]
> I wonder if PM/dHMC would handle this case. 
>
> Would this be a good case and helpful to analyze with PM/dHMC? I would also be very interested how you would model this in PM.

The fastest way to get it working would probably be to make sure the Zygote fallback works (I never tested it, so it almost certainly has bugs), and just encapsulate the random effects components in a function that Zygote can calculate the gradient of.

The fastest way to get that example working and be fast would be to write a `bernoulli_logit_randomeffect` density function and corresponding derivatives. That is the approach I took with my proof of concepts.

But a better idea over the long term, that should be just as fast as the explicit version, is to implement broadcasting (for loops aren't supported yet either). I want something like this:

```julia
pulled_left .~ Bernoulli_logit.( random_effect(a, actor) .+ (bp .+ bpC .* condition) .* prosoc_left .+ X × β ) 
```
to fuse into to a single loop over the data that sums of the density (and accumulates the gradients). Things that need implementing:

- [ ] "Expression template" for matrix-matrix (or matrix-vector, etc) products. My plan right now is for `X × β` to create an object that acts like a lazy `Broadcasted` object, while `X * β` computes the product eagerly. The lazy product will fuse with other broadcast operations. I've started working on this in `PaddedMatrices.jl`.
- [ ] Probability distributions that are broadcasted are going to automatically accumulate a sum, instead of allocating an output.
- [ ] Write the `random_effect` function (or perhaps use a different name), that shows the appropriate behavior in a broadcast.
- [ ] Automatic derivatives for the broadcasted operations. Perhaps I'll lower the broadcasted code:
```julia
julia> Meta.lower(Base, :(pulled_left .~ Bernoulli_logit.( random_effect(a, actor) .+ (bp .+ bpC .* condition) .* prosoc_left .+ X × β ) ))
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope'
1 ─ %1  = random_effect(a, actor)
│   %2  = Base.broadcasted(*, bpC, condition)
│   %3  = Base.broadcasted(+, bp, %2)
│   %4  = Base.broadcasted(*, %3, prosoc_left)
│   %5  = Base.broadcasted(+, %1, %4)
│   %6  = X × β
│   %7  = Base.broadcasted(+, %5, %6)
│   %8  = Base.broadcasted(Bernoulli_logit, %7)
│   %9  = Base.broadcasted(~, pulled_left, %8)
│   %10 = Base.materialize(%9)
└──       return %10
))))
```
and work on these `broadcasted` and `materialize` functions directly.

I intend `y .~ Bernoulli_logit.(α .+ X × β)` to be just as fast as the explicitly written [∂Bernoulli_logit_fmadd](https://github.com/chriselrod/ProbabilityDistributions.jl/blob/master/src/distribution_functions.jl#L122).
Similarly, I'd also replace the ITP functions in the ITP model with broadcasts.

I would like to implement everything needed to get all the StatisticalRethinking models working.
I think implement broadcasting would go a long way in allowing for the flexibility needed to easily specify many different models (given a few extra helpers, like `random_effect(...)`).

Eventually, I'd like to support for loops, too.

I'm supposed to start working on July 29th, on the condition that I'll have defended my dissertation by then -- but I'm still a long way from finishing. These Julia projects will not go in, and my adviser specifically told me I should not touch any of these Julia projects until after I've defended. I have never been much good at following directions, but I really should focus on finishing.

**Comment by goedman** [comment]
Absolutely! Way more important. There is plenty of other stuff I need to do for StatisticalRethinking anyway, so no hurry from my side! Thanks for you help and explanations! I'll close this and my other request for now and reopen them after the summer.
